### ISSUE TITLE
Unable to install apex in windows.

### ISSUE THREAD

**Issue by liuchanfeng165** [NVIDIA/apex#642]
Hi, NVIDA RD,I have read some related issues but cannot solve my problem.could u help me?
CMD using 'pip3  install -v  --global-option="--cpp_ext" --global-option="--cuda_ext" ./'
environment：CUDA9.2 ,torch1.3-cu92
    error: command 'C:\\Program Files\\NVIDIA GPU Computing Toolkit\\CUDA\\v9.2\
\bin\\nvcc.exe' failed with exit status 2
  Running setup.py install for apex ... error
Cleaning up...
  Removing source in C:\Users\CS165\AppData\Local\Temp\pip-req-build-o8wynigr
Removed build tracker 'C:\\Users\\CS165\\AppData\\Local\\Temp\\pip-req-tracker-9
_dl465j'
ERROR: Command "'e:\python36\python3.exe' -u -c 'import setuptools, tokenize;__f
ile__='"'"'C:\\Users\\CS165\\AppData\\Local\\Temp\\pip-req-build-o8wynigr\\setup
.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().repla
ce('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exe
c'"'"'))' --cpp_ext --cuda_ext install --record 'C:\Users\CS165\AppData\Local\Te
mp\pip-record-wjxd4itq\install-record.txt' --single-version-externally-managed -
-compile" failed with error code 1 in C:\Users\CS165\AppData\Local\Temp\pip-req-
build-o8wynigr\
Exception information:
Traceback (most recent call last):
  File "e:\python36\lib\site-packages\pip\_internal\cli\base_command.py", line 1
78, in main
    status = self.run(options, args)
  File "e:\python36\lib\site-packages\pip\_internal\commands\install.py", line 4
14, in run
    use_user_site=options.use_user_site,
  File "e:\python36\lib\site-packages\pip\_internal\req\__init__.py", line 58, i
n install_given_reqs
    **kwargs
  File "e:\python36\lib\site-packages\pip\_internal\req\req_install.py", line 95
1, in install
    spinner=spinner,
  File "e:\python36\lib\site-packages\pip\_internal\utils\misc.py", line 776, in
 call_subprocess
    % (command_desc, proc.returncode, cwd))
pip._internal.exceptions.InstallationError: Command "'e:\python36\python3.exe' -
u -c 'import setuptools, tokenize;__file__='"'"'C:\\Users\\CS165\\AppData\\Local
\\Temp\\pip-req-build-o8wynigr\\setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"'
, open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();
exec(compile(code, __file__, '"'"'exec'"'"'))' --cpp_ext --cuda_ext install --re
cord 'C:\Users\CS165\AppData\Local\Temp\pip-record-wjxd4itq\install-record.txt'
--single-version-externally-managed --compile" failed with error code 1 in C:\Us
ers\CS165\AppData\Local\Temp\pip-req-build-o8wynigr\

**Comment by ptrblck** [comment]
@liuchanfeng165 Are you able to install PyTorch CUDA extensions as described [here](https://pytorch.org/tutorials/advanced/cpp_extension.html)?

**Comment by liuchanfeng165** [comment]
> @liuchanfeng165 Are you able to install PyTorch CUDA extensions as described [here](https://pytorch.org/tutorials/advanced/cpp_extension.html)?

of course,since  the version is 1.1.0 ,I built nms and other examples by the function.

**Comment by liuchanfeng165** [comment]
> @liuchanfeng165 Are you able to install PyTorch CUDA extensions as described [here](https://pytorch.org/tutorials/advanced/cpp_extension.html)?
I confirm it again  ,however it is not working in torch1.3 test -'torch_test_cpp_extension'
#
error: command 'E:\\Program Files (x86)\\Microsoft Visual Studio 14.0\\VC\\BIN\\
x86_amd64\\cl.exe' failed with exit status 2
#

**Comment by jiyuan312986471** [comment]
@liuchanfeng165 Do you have error like `fatal error C1083: Cannot open include fil
e: 'basetsd.h': No such file or directory` just before your `cl.exe failed with exit status 2`?

If so, have you installed your windows SDK?

I had the same problem on my windows 10. After installed Windows 10 SDK I managed to install Apex.

**Comment by xiezhipeng-git** [comment]
I have different error.
  E:\study\machineStudy\project\My_matd3\my_matd3\MARL-code-pytorch\apex\apex\csrc\multi_tensor_axpby_kernel.cu(141): here

  1 error detected in the compilation of "csrc/multi_tensor_axpby_kernel.cu".
  error: command 'C:\\Program Files\\NVIDIA GPU Computing Toolkit\\CUDA\\v11.7\\bin\\nvcc.exe' failed with exit code 4294967295
  error: subprocess-exited-with-error

  × Running setup.py install for apex did not run successfully.
  │ exit code: 1
  ╰─> See above for output.

  note: This error originates from a subprocess, and is likely not a problem with pip.
  full command: 'C:\Users\hasee\AppData\Local\Programs\Python\python-3.9.13\python.exe' -u -c '
