### ISSUE TITLE
cuda 10.1 compilation error

### ISSUE THREAD

**Issue by Qiuzhuang** [NVIDIA/apex#1062]
see this link: https://forums.developer.nvidia.com/t/cuda-10-1-nvidia-youre-now-fixing-gcc-bugs-that-gcc-doesnt-even-have/71063/6

after upgrading cuda to V10.1.168, I can compile apex with gcc-7.
