### ISSUE TITLE
AttributeError: module 'torch.distributed' has no attribute 'new_group'

### ISSUE THREAD

**Issue by gcp** [NVIDIA/apex#104]
```
Traceback (most recent call last):
  File "train.py", line 23, in <module>
    from apex import amp
  File "<frozen importlib._bootstrap>", line 971, in _find_and_load
  File "<frozen importlib._bootstrap>", line 955, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 656, in _load_unlocked
  File "<frozen importlib._bootstrap>", line 626, in _load_backward_compatible
  File "C:\DeepSjeng\train\venv10\lib\site-packages\apex-0.1-py3.6.egg\apex\__init__.py", line 4, in <module>
  File "<frozen importlib._bootstrap>", line 971, in _find_and_load
  File "<frozen importlib._bootstrap>", line 955, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 656, in _load_unlocked
  File "<frozen importlib._bootstrap>", line 626, in _load_backward_compatible
  File "C:\DeepSjeng\train\venv10\lib\site-packages\apex-0.1-py3.6.egg\apex\parallel\__init__.py", line 8, in <module>
AttributeError: module 'torch.distributed' has no attribute 'new_group'
```

**Comment by gcp** [comment]
Reverting 35891b280a76b49d55b5935784e71a0a10ce52f5 fixes it.

**Comment by mcarilli** [comment]
Based on the logic in https://github.com/NVIDIA/apex/commit/35891b280a76b49d55b5935784e71a0a10ce52f5, what your error suggests is that your version of Pytorch has neither torch.distributed.get_default_group nor torch.distributed.new_group.

In https://github.com/NVIDIA/apex/issues/96 you say you're using Pytorch 1.0.  I would expect any build of 1.0 to have either get_default_group or new_group.  Are you still using 1.0 when you see this error?

https://github.com/NVIDIA/apex/commit/35891b280a76b49d55b5935784e71a0a10ce52f5 should work for versions of Pytorch 1.0 both before and after https://github.com/pytorch/pytorch/pull/14767.  I tried
```
>>> from apex import amp
```
with versions of Pytorch before and after https://github.com/pytorch/pytorch/pull/14767 and I did not observe any errors.

**Comment by gcp** [comment]
> Are you still using 1.0 when you see this error?

I am. I made a fresh virtualenv to test, and installed PyTorch with 
```
pip3 install https://download.pytorch.org/whl/cu100/torch-1.0.0-cp36-cp36m-win_amd64.whl
pip3 install torchvision
```

Reading the manual: https://pytorch.org/docs/stable/distributed.html

"PyTorch distributed currently only supports Linux."

So the expectation that one or the other would be available may be wrong.

**Comment by mcarilli** [comment]
Ok, if the backend isn‘t available at all on windows, what you‘re seeing makes sense.  I don‘t have a windows system to test on, but I can make the import checks more lenient to allow the possibility that no backend is available.  

Do you actually need the sync batchnorm, or any distributed utilities?  Or are you simply trying to use amp, and are blocked by the apparent unavailability of the dist backed?

**Comment by gcp** [comment]
I'm just trying to use apex/amp, don't need the extras. But you now get this error as soon as you import the module, so...

**Comment by gcp** [comment]
Fixed in master + PyTorch 1.1.
