### ISSUE TITLE
always AttributeError: module 'torch' has no attribute 'library'

### ISSUE THREAD

**Issue by Cominder** [NVIDIA/apex#1870]
always have
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/root/apex/apex/__init__.py", line 26, in <module>
    from . import normalization
  File "/root/apex/apex/normalization/__init__.py", line 1, in <module>
    from .fused_layer_norm import FusedLayerNorm, MixedFusedLayerNorm, FusedRMSNorm, MixedFusedRMSNorm
  File "/root/apex/apex/normalization/fused_layer_norm.py", line 70, in <module>
    if supports_custom_op():
  File "/root/apex/apex/normalization/fused_layer_norm.py", line 18, in supports_custom_op
    return hasattr(torch.library, "custom_op")
AttributeError: module 'torch' has no attribute 'library'。

no matter cuda10.1+torch1.6.0/1.7.1 or cuda11.1+torch1.8.0 or cuda11.3+torch1.10.1, apex did nnot work!![Image](https://github.com/user-attachments/assets/44003d52-ec17-4c37-b5c6-ca61bda1cf55)

**Comment by GG0614** [comment]
Did you solve it?

**Comment by Cominder** [comment]
> Did you solve it?  你解决了吗？

NO, still bothers me

**Comment by GG0614** [comment]
> > Did you solve it?  你解决了吗？
> 
> NO, still bothers me

you can try apex-22.02-parallel-state,I solve this problem just now
cuda11.3+torch1.10.1+torchvision0.11.2+torchaudio0.10.1

**Comment by Cominder** [comment]
> > > Did you solve it?  你解决了吗？
> > 
> > 
> > NO, still bothers me  不，仍然困扰着我
> 
> you can try apex-22.02-parallel-state,I solve this problem just now你可以试试apex-22.02-parallel-state，我刚刚解决了这个问题 cuda11.3+torch1.10.1+torchvision0.11.2+torchaudio0.10.1

where to get apex-22.02-parallel-state? I can not find it

**Comment by Cominder** [comment]
git clone https://github.com/NVIDIA/apex.git
cd apex
git tag  # if not wanted version
git branch -r
git checkout origin/22.02-parallel-state  # or another vesion
python setup.py install --cuda_ext --cpp_ext
pip3 install -v --no-cache-dir ./

**Comment by GG0614** [comment]
> git clone https://github.com/NVIDIA/apex.git cd apex git tag # if not wanted version git branch -r git checkout origin/22.02-parallel-state # or another vesion python setup.py install --cuda_ext --cpp_ext pip3 install -v --no-cache-dir ./

yes,you can try

**Comment by QLYYLQ** [comment]
> git clone https://github.com/NVIDIA/apex.git cd apex git tag # if not wanted version git branch -r git checkout origin/22.02-parallel-state # or another vesion python setup.py install --cuda_ext --cpp_ext pip3 install -v --no-cache-dir ./

It works in cuda 11.3, thank you a lot

**Comment by rzw520** [comment]
我用这个版本成功解决了
git clone https://github.com/ptrblck/apex.git
cd apex
git checkout apex_no_distributed
pip install -v --no-cache-dir ./

**Comment by Chenhongchang** [comment]
> 我用这个版本成功解决了 git clone https://github.com/ptrblck/apex.git cd apex git checkout apex_no_distributed pip install -v --no-cache-dir ./

thank you

**Comment by ShutaoChen97** [comment]
> 我用这个版本成功解决了 git clone https://github.com/ptrblck/apex.git cd apex git checkout apex_no_distributed pip install -v --no-cache-dir ./

Thanks for sharing! This applies to my conda virtual environment on Ubuntu as well.

**Comment by Ambuj-Choudha** [comment]
> 我用这个版本成功解决了 git clone https://github.com/ptrblck/apex.git cd apex git checkout apex_no_distributed pip install -v --no-cache-dir ./

Haha, legendary ptrblck to the rescue. :))

Thanks for sharing the fix, although I checked the differences in the no-distributed branch, it seems the latest version have those changes already. 
So, I think cloning the original repository (i.e. git clone https://github.com/NVIDIA/apex.git) should also work, imo.

Also, how do people find these fixes?!

**Comment by gudin-hub** [comment]
> git clone https://github.com/NVIDIA/apex.git cd apex git tag # if not wanted version git branch -r git checkout origin/22.02-parallel-state # or another vesion python setup.py install --cuda_ext --cpp_ext pip3 install -v --no-cache-dir ./

可以成功下载，但是print(apex.__version__)会显示AttributeError: module 'apex' has no attribute '__version__'，
print(amp._amp_C.__file__)显示AttributeError: module  apex.amp  has no attribute  _amp_C,
暂时忽略这些错误
ubuntu18.04+cuda10.2+torch1.7.1+torchvision0.8.2
