### ISSUE TITLE
Module 'torch.nn' has no attribute 'backends'

### ISSUE THREAD

**Issue by YuryBolkonsky** [NVIDIA/apex#547]
Pytorch 1.3, Windows10, apex 0.1

<ipython-input-14-a98dc43dd080> in <module>
     10 opt_level = 'O1'
     11 model.cuda()
---> 12 model, optimizer = amp.initialize(model, optimizer, opt_level=opt_level)
     13 scheduler = ReduceLROnPlateau(optimizer, factor=0.5, patience=2)

c:\apps\python3.7.3_64bit\lib\site-packages\apex\amp\frontend.py in initialize(models, optimizers, enabled, opt_level, cast_model_type, patch_torch_functions, keep_batchnorm_fp32, master_weights, loss_scale, cast_model_outputs, num_losses, verbosity, min_loss_scale, max_loss_scale)
    355         maybe_print("{:22} : {}".format(k, v), True)
    356 
--> 357     return _initialize(models, optimizers, _amp_state.opt_properties, num_losses, cast_model_outputs)
    358 
    359 

c:\apps\python3.7.3_64bit\lib\site-packages\apex\amp\_initialize.py in _initialize(models, optimizers, properties, num_losses, cast_model_outputs)
    239     if properties.patch_torch_functions:
    240         # handle is unused here. It's accessible later through a global value anyway.
--> 241         handle = amp_init(loss_scale=properties.loss_scale, verbose=(_amp_state.verbosity == 2))
    242         for optimizer in optimizers:
    243             # Disable Amp casting for the optimizer step, because it should only be

c:\apps\python3.7.3_64bit\lib\site-packages\apex\amp\amp.py in init(enabled, loss_scale, enable_caching, verbose, allow_banned)
     99             try_caching = (cast_fn == utils.maybe_half)
    100             wrap.cached_cast(module.MODULE, fn, cast_fn, handle,
--> 101                              try_caching, verbose)
    102 
    103     # 1.5) Pre-0.4, put the blacklist methods on HalfTensor and whitelist

c:\apps\python3.7.3_64bit\lib\site-packages\apex\amp\wrap.py in cached_cast(mod, fn, cast_fn, handle, try_caching, verbose)
     31 def cached_cast(mod, fn, cast_fn, handle,
     32                 try_caching=False, verbose=False):
---> 33     if not utils.has_func(mod, fn):
     34         return
     35 

c:\apps\python3.7.3_64bit\lib\site-packages\apex\amp\utils.py in has_func(mod, fn)
    130 
    131 def has_func(mod, fn):
--> 132     if isinstance(mod, torch.nn.backends.backend.FunctionBackend):
    133         return fn in mod.function_classes
    134     elif isinstance(mod, dict):

AttributeError: module 'torch.nn' has no attribute 'backends'

**Comment by PistonY** [comment]
Same issue with Pytorch 1.3, Pytorch 1.2 is ok.
os: Ubuntu 18.04, Cuda 10.1

**Comment by PistonY** [comment]
@mcarilli @ptrblck Could you please have a look at this.It seems not work with Pytorch 1.3.

**Comment by PistonY** [comment]
Please try update your version.
I found that `if isinstance(mod, torch.nn.backends.backend.FunctionBackend):` has been del from the code.

**Comment by PistonY** [comment]
I've tried, it works.

**Comment by YuryBolkonsky** [comment]
Works

**Comment by bling-legend** [comment]
I'm having the same issue can someone explain how it was solved and how I can solve it, I'm working on kaggle

**Comment by Alasile** [comment]
> Please try reinstall this. I found that `if isinstance(mod, torch.nn.backends.backend.FunctionBackend):` has been del from the code.

hello, I am having the same issue ,could you tell which version apex can i reinstall ?

**Comment by userguazi** [comment]
how to fix it？

**Comment by STITCHESHHH** [comment]
> I'm having the same issue can someone explain how it was solved and how I can solve it, I'm working on kaggle

hello,which version apex?friend!

**Comment by ikranergiz** [comment]
I got the same error. Please check your functions in apex/amp/utils.py, which should be like this:

def has_func(mod, fn):
    if isinstance(mod, dict):
        return fn in mod
    else:
        return hasattr(mod, fn)

def get_func(mod, fn):
    if isinstance(mod, dict):
        return mod[fn]
    else:
        return getattr(mod, fn)

def set_func(mod, fn, new_fn):
    if isinstance(mod, dict):
        mod[fn] = new_fn
    else:
        setattr(mod, fn, new_fn)

In github repo, these functions was defined like this but when I cloned the repo, it was different. So it should be changed.
I also needed to check and change like this. It worked for me.
